import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Define your Helvetica Now Display font
const helvetica = localFont({
  src: [
    {
      path: "./fonts/HelveticaNowDisplay-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-Light.eot",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-Light.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/HelveticaNowDisplay-Light.woff",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-helvetica",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${helvetica.variable}`}>
      <head>
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <meta
          name="keywords"
          content="sendNow, chat, messaging, secure, fast, reliable, instant, private, encrypted, group, one-on-one, video, audio, file, location, status, notification, message, typing, emoji, reaction, sticker, voice, call, video call, text, image, audio, video, document, location, status, notification, message, typing, emoji, reaction, sticker, voice, call, video call, text, image, audio, video, document, location, status, notification, message, typing, emoji, reaction, sticker, voice, call, video call"
        />
        <meta
          name="description"
          content="sendNow - Introducing Chat – Instant, Secure, Smarter Messaging"
        />
        <meta name="themes" content="sendNow" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="font-sans antialiased">{children}</body>
    </html>
  );
}
